# Generated by Django 5.1.1 on 2024-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='open_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
