# Generated by Django 5.1.1 on 2024-10-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_user_id_orders_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='monetary_amount',
            new_name='dollar_amount',
        ),
        migrations.AddField(
            model_name='orders',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], default='NONE', max_length=4),
            preserve_default=False,
        ),
    ]
