# Generated by Django 5.1.1 on 2024-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_monetary_amount_orders_dollar_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')], max_length=5),
        ),
    ]
