# Generated by Django 5.1.1 on 2024-10-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_orders_unrealised_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
