# Generated by Django 5.1.1 on 2024-10-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_orders_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='null'),
        ),
    ]
