# Generated by Django 5.1.1 on 2024-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_orders_trade_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dollar_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='unit_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
