# Generated by Django 5.1.1 on 2024-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(blank=True, null=True, decimal_places=2, default=None, max_digits=100),
        ),
    ]
