# Generated by Django 5.1.1 on 2024-10-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_emailconfirmtokens_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='api_key',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emailconfirmtokens',
            name='created_at',
            field=models.IntegerField(default=1729628199),
        ),
    ]
