# Generated by Django 5.1.1 on 2024-10-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmtokens',
            name='created_at',
            field=models.IntegerField(default=1729635783),
        ),
    ]
